### ISSUE TITLE
Improved graphs chapter 

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-docs#951]
Subset taken from https://github.com/plotly/dash-docs/issues/740:

- [ ] document `extendData`  and `restyleData` (#488)
- [ ] example using uirevision (see Alex of community forum post!!)
- [ ] document transitions (see #660 )
- [ ] document graph responsiveness (see #720)
- [ ] explain how plotly.js is used under the hood and how to check the plotly.js version and updated it if necessary (#723 )
- [ ] Describe exactly which properties _and interactions_ (e.g. clicking on legends, zooming in or out, clicking on buttons in the modebar, clicking on points) are available in `restyleData` vs `relayoutData` etc.
